### PR TITLE
fix some script warning and error

### PR DESCRIPTION
**Pull request by lxf1992521**

### CODE REVIEW

**Comment by Tontonitch** [comment]
for the "fix perl regex warning", what is the warning message you receive?

**Comment by lxf1992521** [comment]
1. perl script interpreter error
    if using ''#!/usr/bin/env perl -w", will give the error:
    ——————————————————————————————————
    /usr/bin/env: perl -w: No such file or directory
    $ less /usr/lib64/nagios/plugins/check_interface_table_v3t
    ——————————————————————————————————
    and after google, you will find this interpreter will not vaild in centos 6/7,at least.

2.fix perl regex warning
    ——————————————————————————————————
    $ /usr/lib64/nagios/plugins/check_interface_table_v3t > /dev/null 
    \1 better written as $1 at /usr/lib64/interfacetable_v3t/SnmpUtils.pm line 743.
    \2 better written as $2 at /usr/lib64/interfacetable_v3t/SnmpUtils.pm line 743.
    ——————————————————————————————————

**Comment by Tontonitch** [comment]
Ok for the regex.

For the 1st point, I use RedHat 7 (= CentOS 7) and no issue. Your error message says that the perl binary cannot be found using the PATH variable.

```
[root@monitorsrv1 ~]# /usr/bin/env toto
/usr/bin/env: toto: No such file or directory
[root@monitorsrv1 ~]#
[root@monitorsrv1 ~]# /usr/bin/env perl -v

This is perl 5, version 16, subversion 3 (v5.16.3) built for x86_64-linux-thread-multi
(with 33 registered patches, see perl -V for more detail)

Copyright 1987-2012, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.

[root@monitorsrv1 ~]#
[root@monitorsrv1 ~]# which perl
/usr/bin/perl
[root@monitorsrv1 ~]#
[root@monitorsrv1 ~]# env | grep PATH | grep "/usr/bin"
PATH=/root/perl5/bin:/opt/rh/rh-php71/root/usr/bin:/opt/rh/rh-php71/root/usr/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin
[root@monitorsrv1 ~]#
```

**Comment by lxf1992521** [comment]
——————————————————————————————————
$ lsb_release -d
Description:	CentOS release 6.4 (Final)
$ echo '#!/usr/bin/env perl -v' > a.pl && chmod +x a.pl && ./a.pl
/usr/bin/env: perl -v: No such file or directory
——————————————————————————————————

——————————————————————————————————
$ lsb_release -d
Description:	CentOS Linux release 7.4.1708 (Core) 
$ echo '#!/usr/bin/env perl -w' > a.pl && chmod +x a.pl && ./a.pl
/usr/bin/env: perl -w: No such file or directory
——————————————————————————————————

**Comment by lxf1992521** [comment]
Yes, I found "favicon.ico" 404 request in apache logs, so fix with it.

**Pull request closed without merging**
